### ISSUE TITLE
Change the DBs used away from Redis and Maria

### ISSUE THREAD

**Issue by AeonRemnant** [pyrohost/pyrodactyl#122]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Simply put there's some higher performance options that can be relatively easily migrated toward.

### Describe the solution you'd like.

Firstly, Postgres > Maria, this would require a bit of work but be a significant step up over Maria. 
Secondly, KeyDB > Redis, KeyDB is a dropin replacement for Redis, it's multithreaded and a LOT faster, a single KeyDB install is as fast as a 7 node Redis cluster. It's 1:1 Redis compatible and doesn't require any specific rewrites. 

In the event KeyDB is veto'd, I very much would love to see switching to Valkey, the TL;DR is Valkey is open source Redis ever since Redis closed source. 

Given this is Docker Compose driven, it makes sense to use higher performance alt softwares.

**Comment by naterfute** [comment]
I support the Postgres movement as I use Postgres in almost everything I build. This would require us to make a few big changes such as making a way to migrate from Maria to Postgres, but the Redis to KeyDB, or even Valkey is definitely possible, sense it's such an easy change because keyDB is a drop in replacement, I might update the docker-compose to use that after I test it a bit. The maria to postgres is quite the issue, as they are seperate database with their own commands, while they are very similar, it's definitely going to be a challenge to do.

**Comment by naterfute** [comment]
And there's also the issue of pterodactyl to pyrodactyl compatibility, I would have to talk for a while before even beginning to implement this

**Comment by naterfute** [comment]
Unless I get a pr to implement that with easy migrations, I'm going to close this
